### ISSUE TITLE
Arithmetic

### ISSUE THREAD

**Issue by boopdoop** [liamgens/BuckNaked#12]
As a developer, I'd like to be able to perform basic arithmetic operations, as defined by the language specification guide.

**Comment by bmmcmahon** [comment]
# Acceptance Tests
## Add Test
Type the code into the editor: 
```
var x 1
add x 2 x
print x
add x x x
print x
```
This should print 
```
3
6
``` 
in the output window, because x is originally set to 1, then to the value of 1 + 2, then to the value of x + x, which is equal to 3 + 3. 

## Sub Test
Type the code into the editor: 
```
var x 1
sub x 2 x
print x
add x x x
print x
```
This should print 
```
-1
-2
``` 
in the output window, because x is originally set to 1, then to the value of 1 - 2, then to the value of x - x, which is equal to -1 + (-1). 

## Mul Test
Type the code into the editor: 
```
var x 
mul 2 2 x
print x
mul x x x
print x
```
This should print 
```
4
16
``` 
in the output window, because x is originally set to the value of 2 * 2, then to the value of x + x, which is equal to 4 * 4. 

## Div Test
Type the code into the editor: 
```
var x 
div 4 2 x
print x
div x x x
print x
```
This should print 
```
2
1
``` 
in the output window, because x is originally set to the value of 4 / 2, then to the value of x / x, which is equal to 2 / 2. 

## Mod Test
Type the code into the editor: 
```
var x 
mod 400 22 x
print x
mod x x x
print x
```
This should print 
```
4
0
``` 
in the output window, because x is originally set to the value of 400 % 22, then to the value of x % x, which is equal to 4 / 4. 

## Longer Test
Type the code into the editor: 
```
var x
var y 22
mod 400 22 x (4)
var z
mul x y z (88)
div z x x (22)
add x z y
print x
print y
print z
```
This should print 
```
22
110
88
``` 
in the output window.
